apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #change the name to match the network path this 
  #argocd agent is responsible for
  name: nwpath-cluster1-cluster2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #change the repoURL to point to your gitops repo
    repoURL: https://github.com/wrichter/crc-gitops.git
    targetRevision: HEAD
    #change the path to point to the directory in the gitops repo
    #that represents the execution environment
    path: deployment/nwpath-cluster1-cluster2
  destination:
    server: https://kubernetes.default.svc
    #change the namespace to the one which represents the network path
    namespace: manuela-networkpathoperator
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
