apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-prod-machine-sensor
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sa-mw-dach/manuela-gitops.git
    targetRevision: HEAD
    path: config/instances/manuela-prod/machine-sensor
  destination:
    server: https://kubernetes.default.svc
    namespace: manuela-prod-machine-sensor
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
    - /spec/tags
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image